[workspace]
members = ["yadi", "yadi_derive"]
resolver = "2"

[patch.crates-io]
yadi = { path = "yadi" }

[workspace.dependencies]
proc-macro2 = { version = "1", default-features = false }
quote = { version = "1", default-features = false }
syn = { version = "2", default-features = false }